
CREATE OR REPLACE VIEW VW_REVENUE_BY_DAY AS
SELECT
    D.FULL_DATE,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.FULL_DATE;

CREATE OR REPLACE VIEW VW_TOP_CUSTOMERS AS
SELECT
    C.CUSTOMER_ID,
    SUM(F.AMOUNT) AS TOTAL_SPENT
FROM FACT_EVENTS F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_ID;

CREATE OR REPLACE VIEW VW_REVENUE_BY_EVENT_TYPE AS
SELECT
    E.EVENT_TYPE,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_EVENT_TYPE E
    ON F.EVENT_TYPE_KEY = E.EVENT_TYPE_KEY
GROUP BY E.EVENT_TYPE;

CREATE OR REPLACE VIEW VW_EVENT_COUNTS AS
SELECT
    E.EVENT_TYPE,
    COUNT(*) AS EVENT_COUNT
FROM FACT_EVENTS F
JOIN DIM_EVENT_TYPE E
    ON F.EVENT_TYPE_KEY = E.EVENT_TYPE_KEY
GROUP BY E.EVENT_TYPE;

CREATE OR REPLACE VIEW VW_DAILY_KPI AS
SELECT
    D.FULL_DATE,
    COUNT(*) AS TOTAL_EVENTS,
    SUM(F.AMOUNT) AS TOTAL_REVENUE,
    AVG(F.AMOUNT) AS AVG_AMOUNT
FROM FACT_EVENTS F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.FULL_DATE;

SHOW VIEWS;

TRUNCATE TABLE KAFKA_EVENTS_SILVER;

DROP DATABASE IF EXISTS KAFKA_DB;

CREATE DATABASE KAFKA_DB;

CREATE SCHEMA KAFKA_DB.STREAMING;

USE DATABASE KAFKA_DB;
USE SCHEMA STREAMING;

CREATE OR REPLACE TABLE KAFKA_EVENTS_SILVER (

    EVENT_ID STRING,
    SESSION_ID STRING,

    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    CITY STRING,
    COUNTRY STRING,
    AGE NUMBER,
    GENDER STRING,
    SEGMENT STRING,

    CHANNEL STRING,

    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,

    UNIT_PRICE NUMBER(10,2),
    QUANTITY NUMBER,
    DISCOUNT NUMBER,
    SUBTOTAL NUMBER(10,2),
    AMOUNT NUMBER(10,2),

    ORDER_STATUS STRING,

    DEVICE STRING,
    PAYMENT_METHOD STRING,

    EVENT_TYPE STRING,
    CURRENCY STRING,

    EVENT_TIMESTAMP TIMESTAMP_NTZ,

    KAFKA_INGEST_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DESC TABLE KAFKA_EVENTS_SILVER;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    CITY STRING,
    COUNTRY STRING,
    AGE NUMBER,
    GENDER STRING,
    SEGMENT STRING
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,
    UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE DIM_EVENT_TYPE (
    EVENT_TYPE_KEY NUMBER AUTOINCREMENT,
    EVENT_TYPE STRING
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    DAY_NAME STRING,
    WEEK_NUM NUMBER
);

CREATE OR REPLACE TABLE DIM_CHANNEL (
    CHANNEL_KEY NUMBER AUTOINCREMENT,
    CHANNEL STRING
);

CREATE OR REPLACE TABLE DIM_DEVICE (
    DEVICE_KEY NUMBER AUTOINCREMENT,
    DEVICE STRING
);

CREATE OR REPLACE TABLE DIM_PAYMENT_METHOD (
    PAYMENT_METHOD_KEY NUMBER AUTOINCREMENT,
    PAYMENT_METHOD STRING
);

CREATE OR REPLACE TABLE DIM_ORDER_STATUS (
    ORDER_STATUS_KEY NUMBER AUTOINCREMENT,
    ORDER_STATUS STRING
);

CREATE OR REPLACE TABLE DIM_CURRENCY (
    CURRENCY_KEY NUMBER AUTOINCREMENT,
    CURRENCY STRING
);

CREATE OR REPLACE TABLE FACT_EVENTS (
    EVENT_ID STRING,
    SESSION_ID STRING,

    CUSTOMER_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    EVENT_TYPE_KEY NUMBER,
    DATE_KEY NUMBER,
    CHANNEL_KEY NUMBER,
    DEVICE_KEY NUMBER,
    PAYMENT_METHOD_KEY NUMBER,
    ORDER_STATUS_KEY NUMBER,
    CURRENCY_KEY NUMBER,

    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    AMOUNT NUMBER(10,2)
);


MERGE INTO DIM_CUSTOMER AS T
USING (
    SELECT DISTINCT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        COUNTRY,
        AGE,
        GENDER,
        SEGMENT
    FROM KAFKA_EVENTS_SILVER
) AS S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN NOT MATCHED THEN
INSERT (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    COUNTRY,
    AGE,
    GENDER,
    SEGMENT
)
VALUES (
    S.CUSTOMER_ID,
    S.CUSTOMER_NAME,
    S.CITY,
    S.COUNTRY,
    S.AGE,
    S.GENDER,
    S.SEGMENT
);


MERGE INTO DIM_PRODUCT AS T
USING (
    SELECT DISTINCT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        BRAND,
        UNIT_PRICE
    FROM KAFKA_EVENTS_SILVER
) AS S
ON T.PRODUCT_ID = S.PRODUCT_ID

WHEN NOT MATCHED THEN
INSERT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    UNIT_PRICE
)
VALUES (
    S.PRODUCT_ID,
    S.PRODUCT_NAME,
    S.CATEGORY,
    S.BRAND,
    S.UNIT_PRICE
);

MERGE INTO DIM_EVENT_TYPE T
USING (
    SELECT DISTINCT EVENT_TYPE
    FROM KAFKA_EVENTS_SILVER
) S
ON T.EVENT_TYPE = S.EVENT_TYPE

WHEN NOT MATCHED THEN
INSERT (EVENT_TYPE)
VALUES (S.EVENT_TYPE);

MERGE INTO DIM_CHANNEL T
USING (
    SELECT DISTINCT CHANNEL
    FROM KAFKA_EVENTS_SILVER
) S
ON T.CHANNEL = S.CHANNEL

WHEN NOT MATCHED THEN
INSERT (CHANNEL)
VALUES (S.CHANNEL);

MERGE INTO DIM_DEVICE T
USING (
    SELECT DISTINCT DEVICE
    FROM KAFKA_EVENTS_SILVER
) S
ON T.DEVICE = S.DEVICE

WHEN NOT MATCHED THEN
INSERT (DEVICE)
VALUES (S.DEVICE);

MERGE INTO DIM_PAYMENT_METHOD T
USING (
    SELECT DISTINCT PAYMENT_METHOD
    FROM KAFKA_EVENTS_SILVER
) S
ON T.PAYMENT_METHOD = S.PAYMENT_METHOD

WHEN NOT MATCHED THEN
INSERT (PAYMENT_METHOD)
VALUES (S.PAYMENT_METHOD);

MERGE INTO DIM_ORDER_STATUS T
USING (
    SELECT DISTINCT ORDER_STATUS
    FROM KAFKA_EVENTS_SILVER
) S
ON T.ORDER_STATUS = S.ORDER_STATUS

WHEN NOT MATCHED THEN
INSERT (ORDER_STATUS)
VALUES (S.ORDER_STATUS);

MERGE INTO DIM_CURRENCY T
USING (
    SELECT DISTINCT CURRENCY
    FROM KAFKA_EVENTS_SILVER
) S
ON T.CURRENCY = S.CURRENCY

WHEN NOT MATCHED THEN
INSERT (CURRENCY)
VALUES (S.CURRENCY);

MERGE INTO DIM_DATE T
USING (
    SELECT DISTINCT
        TO_NUMBER(TO_CHAR(EVENT_TIMESTAMP,'YYYYMMDD')) AS DATE_KEY,
        CAST(EVENT_TIMESTAMP AS DATE) AS FULL_DATE,
        YEAR(EVENT_TIMESTAMP) AS YEAR,
        MONTH(EVENT_TIMESTAMP) AS MONTH,
        DAY(EVENT_TIMESTAMP) AS DAY,
        DAYNAME(EVENT_TIMESTAMP) AS DAY_NAME,
        WEEK(EVENT_TIMESTAMP) AS WEEK_NUM
    FROM KAFKA_EVENTS_SILVER
) S
ON T.DATE_KEY = S.DATE_KEY

WHEN NOT MATCHED THEN
INSERT (
    DATE_KEY,
    FULL_DATE,
    YEAR,
    MONTH,
    DAY,
    DAY_NAME,
    WEEK_NUM
)
VALUES (
    S.DATE_KEY,
    S.FULL_DATE,
    S.YEAR,
    S.MONTH,
    S.DAY,
    S.DAY_NAME,
    S.WEEK_NUM
);

MERGE INTO FACT_EVENTS T
USING (
    SELECT
        S.EVENT_ID,
        S.SESSION_ID,

        C.CUSTOMER_KEY,
        P.PRODUCT_KEY,
        E.EVENT_TYPE_KEY,
        D.DATE_KEY,
        CH.CHANNEL_KEY,
        DV.DEVICE_KEY,
        PM.PAYMENT_METHOD_KEY,
        OS.ORDER_STATUS_KEY,
        CUR.CURRENCY_KEY,

        S.QUANTITY,
        S.UNIT_PRICE,
        S.DISCOUNT,
        S.SUBTOTAL,
        S.AMOUNT

    FROM KAFKA_EVENTS_SILVER S

    JOIN DIM_CUSTOMER C
        ON S.CUSTOMER_ID = C.CUSTOMER_ID

    JOIN DIM_PRODUCT P
        ON S.PRODUCT_ID = P.PRODUCT_ID

    JOIN DIM_EVENT_TYPE E
        ON S.EVENT_TYPE = E.EVENT_TYPE

    JOIN DIM_DATE D
        ON CAST(S.EVENT_TIMESTAMP AS DATE) = D.FULL_DATE

    JOIN DIM_CHANNEL CH
        ON S.CHANNEL = CH.CHANNEL

    JOIN DIM_DEVICE DV
        ON S.DEVICE = DV.DEVICE

    JOIN DIM_PAYMENT_METHOD PM
        ON S.PAYMENT_METHOD = PM.PAYMENT_METHOD

    JOIN DIM_ORDER_STATUS OS
        ON S.ORDER_STATUS = OS.ORDER_STATUS

    JOIN DIM_CURRENCY CUR
        ON S.CURRENCY = CUR.CURRENCY
) S
ON T.EVENT_ID = S.EVENT_ID

WHEN NOT MATCHED THEN
INSERT (
    EVENT_ID,
    SESSION_ID,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    EVENT_TYPE_KEY,
    DATE_KEY,
    CHANNEL_KEY,
    DEVICE_KEY,
    PAYMENT_METHOD_KEY,
    ORDER_STATUS_KEY,
    CURRENCY_KEY,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    SUBTOTAL,
    AMOUNT
)
VALUES (
    S.EVENT_ID,
    S.SESSION_ID,
    S.CUSTOMER_KEY,
    S.PRODUCT_KEY,
    S.EVENT_TYPE_KEY,
    S.DATE_KEY,
    S.CHANNEL_KEY,
    S.DEVICE_KEY,
    S.PAYMENT_METHOD_KEY,
    S.ORDER_STATUS_KEY,
    S.CURRENCY_KEY,
    S.QUANTITY,
    S.UNIT_PRICE,
    S.DISCOUNT,
    S.SUBTOTAL,
    S.AMOUNT
);
CREATE OR REPLACE VIEW VW_REVENUE_BY_DAY AS
SELECT
    D.FULL_DATE,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.FULL_DATE
ORDER BY D.FULL_DATE;

CREATE OR REPLACE VIEW VW_DAILY_KPI AS
SELECT
    D.FULL_DATE,
    COUNT(*) AS TOTAL_EVENTS,
    SUM(F.AMOUNT) AS TOTAL_REVENUE,
    AVG(F.AMOUNT) AS AVG_AMOUNT
FROM FACT_EVENTS F
JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.FULL_DATE
ORDER BY D.FULL_DATE;

CREATE OR REPLACE VIEW VW_REVENUE_BY_EVENT_TYPE AS
SELECT
    E.EVENT_TYPE,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_EVENT_TYPE E
    ON F.EVENT_TYPE_KEY = E.EVENT_TYPE_KEY
GROUP BY E.EVENT_TYPE;

CREATE OR REPLACE VIEW VW_TOP_CUSTOMERS AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.AMOUNT) AS TOTAL_SPENT
FROM FACT_EVENTS F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

CREATE OR REPLACE VIEW VW_EVENT_COUNTS AS
SELECT
    E.EVENT_TYPE,
    COUNT(*) AS EVENT_COUNT
FROM FACT_EVENTS F
JOIN DIM_EVENT_TYPE E
    ON F.EVENT_TYPE_KEY = E.EVENT_TYPE_KEY
GROUP BY E.EVENT_TYPE;

CREATE OR REPLACE VIEW VW_REVENUE_BY_PRODUCT AS
SELECT
    P.PRODUCT_NAME,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_PRODUCT P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC;

CREATE OR REPLACE VIEW VW_REVENUE_BY_CITY AS
SELECT
    C.CITY,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_CUSTOMER C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CITY;

CREATE OR REPLACE VIEW VW_REVENUE_BY_PAYMENT_METHOD AS
SELECT
    P.PAYMENT_METHOD,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_PAYMENT_METHOD P
ON F.PAYMENT_METHOD_KEY = P.PAYMENT_METHOD_KEY
GROUP BY P.PAYMENT_METHOD;

CREATE OR REPLACE VIEW VW_REVENUE_BY_DEVICE AS
SELECT
    D.DEVICE,
    SUM(F.AMOUNT) AS REVENUE
FROM FACT_EVENTS F
JOIN DIM_DEVICE D
ON F.DEVICE_KEY = D.DEVICE_KEY
GROUP BY D.DEVICE;